version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mp123
    container_name: mpdb
    volumes:
      - ./postgres:/var/lib/postgresql/data